#!/bin/bash
find . -name "*.html" -exec bash -c '[ ! -f "$(dirname "$(dirname "{}")")/$(basename "{}")" ] || [ "{}" -nt "$(dirname "$(dirname "{}")")/$(basename "{}")" ] && cat "{}" | tee "$(dirname "$(dirname "{}")")/$(basename "{}")"' 
